---
- name: "weave | init"
  command: cp /opt/pidalio/scripts/weave/weave-init.sh /opt/weave-init.sh

- name: "weave | init level up"
  command: chmod +x /opt/weave-init.sh

- name: "weave | weave-network.target"
  command: cp /opt/pidalio/scripts/weave/weave-network.target /etc/systemd/system/weave-network.target

- name: "weave | weave-init.service"
  command: cp /opt/pidalio/scripts/weave/weave-init.service /etc/systemd/system/weave-init.service

- name: "weave | 10-weave.network"
  command: cp /opt/pidalio/scripts/weave/10-weave.network /etc/systemd/system/10-weave.network

- name: "weave | install-weave.service"
  command: cp /opt/pidalio/scripts/weave/install-weave.service /etc/systemd/system/install-weave.service

- name: "weave | weave.service"
  command: cp /opt/pidalio/scripts/weave/weave.service /etc/systemd/system/weave.service

- name: "weave | weaveproxy.service"
  command: cp /opt/pidalio/scripts/weave/weaveproxy.service /etc/systemd/system/weaveproxy.service

- name: "weave | weaveplugin.service"
  command: cp /opt/pidalio/scripts/weave/weaveplugin.service /etc/systemd/system/weaveplugin.service

- name: "weave | start weave-network.target"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: weave-network.target

- name: "weave | start weave-init.service"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: weave-init.service

#- name: "weave | start 10-weave.network"
#  systemd:
#    daemon_reload: yes
#    state: started
#    name: 10-weave.network

- name: "weave | start install-weave.service"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: install-weave.service

- name: "weave | start weave.service"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: weave.service

- name: "weave | start weaveproxy.service"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: weaveproxy.service

- name: "weave | start weaveplugin.service"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: weaveplugin.service