---
  - name: "etcd | cp config for proxy"
    command: cp /opt/pidalio/scripts/etcd_fleet/etcd.service /etc/systemd/system/etcd.service
    when: "inventory_hostname == groups.k8s_attach_fip_fr1[0]"

  - name: "etcd | start etcd"
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: etcd.service
    when: "inventory_hostname == groups.k8s_attach_fip_fr1[0]"

  - name: "etcd | cp config for proxy"
    command: cp /opt/pidalio/scripts/etcd_fleet/etcd-proxy.service /etc/systemd/system/etcd-proxy.service
    when: "inventory_hostname != groups.k8s_attach_fip_fr1[0]"

  - name: "etcd | start etcd-proxy"
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: etcd-proxy.service
    when: "inventory_hostname != groups.k8s_attach_fip_fr1[0]"

  - name: "fleet | start"
    systemd:
      state: started
      name: fleet
